//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samoletik.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aircraft
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aircraft()
        {
            this.FlightSchedule = new HashSet<FlightSchedule>();
        }
    
        public int IDAircraft { get; set; }
        public int IDAircraftStatus { get; set; }
        public string AircraftModelName { get; set; }
        public Nullable<int> NumberOfSeats { get; set; }
        public Nullable<int> Range { get; set; }
        public Nullable<int> MaximumSpeed { get; set; }
        public Nullable<int> YearOfManufacture { get; set; }
    
        public virtual AircraftStatus AircraftStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightSchedule> FlightSchedule { get; set; }
    }
}
