//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samoletik.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightSchedule
    {
        public int IDFlightSchedule { get; set; }
        public Nullable<int> IDFlights { get; set; }
        public Nullable<int> IDAircraft { get; set; }
        public string DayOfTheWeek { get; set; }
        public System.DateTime DepartureTime { get; set; }
        public System.DateTime ArrivalTime { get; set; }
    
        public virtual Aircraft Aircraft { get; set; }
        public virtual Flights Flights { get; set; }
    }
}
