//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samoletik.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int IDPayments { get; set; }
        public int IDBooking { get; set; }
        public int IDPaymentMethod { get; set; }
        public int IDEmployees { get; set; }
        public int IDPaymentStatus { get; set; }
        public System.DateTime PaymentDate { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual PaymentStatus PaymentStatus { get; set; }
    }
}
